### ISSUE TITLE
Production Build - Uncaught (in promise) TypeError: Failed to fetch dynamically imported module/assets/mapViewDeps.7d58fb8c.js

### ISSUE THREAD

**Issue by MapocalypseNow** [andygup/vite-jsapi#1]
Hi,

I've been looking at using Vite and the arcgis JS API. 

It seems to work as expected with the vite dev server, however running (and attempting to use) the production build I get the following error: Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: <baseurl>/vite-jsapi/assets/mapViewDeps.7d58fb8c.js

I'm wondering whether I'm missing some config in doing a production build?

**Comment by andygup** [comment]
@MapocalypseNow you can find a simple, downloadable project using @arcgis/core on this SDK sample page => https://developers.arcgis.com/javascript/latest/sample-code/intro-mapview/. Just click the "Download ESM sample button". That sample works with `npm run build`.

**Comment by MapocalypseNow** [comment]
Thanks @andygup I think it may be an issue related to an update of Vite!

Essentially there was a [subtle change at version 2.9 of vite around the default chunk strategy used](https://vitejs.dev/guide/build.html#chunking-strategy ). 

Adding the following config resolved my issues:

```
import { defineConfig } from "vite";
import { splitVendorChunkPlugin } from 'vite'

// https://vitejs.dev/config/
export default defineConfig({
    base: "/vite-jsapi/",
    plugins: [splitVendorChunkPlugin()],
});
```

**Comment by MapocalypseNow** [comment]
working build: [https://mapocalypsenow.github.io/vite-jsapi/](https://mapocalypsenow.github.io/vite-jsapi/)
working fork: [https://github.com/MapocalypseNow/vite-jsapi](https://github.com/MapocalypseNow/vite-jsapi)

**Comment by andygup** [comment]
Thanks @MapocalypseNow. I also updated this repo to the latest Vite `4.1.1`.
